"""Generated, human-readable files: role playbooks, constitution fragments, schemas, dist outputs."""

import json
from pathlib import Path

from . import index, schemas

NOTE = "<!-- Generated from registry/roles/{id}.yaml by `open-skill build`. Edit the YAML, not this file. -->"


def _skill_line(reg, sid: str) -> str:
    s = reg.skills.get(sid, {})
    desc = (s.get("description") or "").split(". ")[0].rstrip(".")
    return f"`{sid}`" + (f" — {desc}" if desc else "")


def role_playbook(reg, rid: str) -> str:
    r = reg.roles[rid]
    lines = [NOTE.format(id=rid), "", f"# {r['name']} playbook", "", r["summary"], "",
             f"**Characteristic risk:** {r['risk']}", "", "## Principles", ""]
    lines += [f"- {c}" for c in r["constitution"]]
    lines += ["", "## Skills by phase", "", "| Phase | Primary | Alternatives |", "|---|---|---|"]
    order = [p["id"] for p in reg.taxonomy["phases"]]
    for ph in order:
        entry = (r.get("phases") or {}).get(ph)
        if not entry:
            continue
        prim = "<br>".join(_skill_line(reg, s) for s in entry.get("primary", [])) or "—"
        alt = "<br>".join(f"`{s}`" for s in entry.get("alternatives", [])) or "—"
        if entry.get("note"):
            prim += f"<br>*{entry['note']}*"
        lines.append(f"| {ph} | {prim} | {alt} |")
    if r.get("seeds"):
        lines += ["", "## Starter knowledge", ""] + [f"- {s}" for s in r["seeds"]]
    if r.get("signals"):
        lines += ["", "## Project signals", "", ", ".join(f"`{s}`" for s in r["signals"])]
    if r.get("handoff"):
        lines += ["", "## Hand-offs", ""] + [f"- {k} → `{v}` playbook" for k, v in r["handoff"].items()]
    return "\n".join(lines) + "\n"


def constitution_fragment(reg, rid: str) -> str:
    r = reg.roles[rid]
    body = "\n".join(f"- **{c.split(':')[0]}**" + (f":{c.split(':', 1)[1]}" if ":" in c else "") for c in r["constitution"])
    return (f"{NOTE.format(id=rid)}\n\n### {r['name']} principles\n\n"
            f"Merge into `.specify/memory/constitution.md` for projects where this role leads.\n\n{body}\n")


def roles_index(reg) -> str:
    lines = ["<!-- Generated by `open-skill build`. -->", "", "# Role playbooks", "",
             "| Family | Role | Risk |", "|---|---|---|"]
    for fam, members in reg.taxonomy["role_families"].items():
        for rid in members:
            if rid in reg.roles:
                lines.append(f"| {fam} | [{reg.roles[rid]['name']}]({rid}.md) | {reg.roles[rid]['risk']} |")
    return "\n".join(lines) + "\n"


def outputs(reg, root: Path) -> dict[Path, str]:
    """Every generated text file, keyed by path. `build --check` compares these with disk."""
    root = Path(root)
    out: dict[Path, str] = {}
    refs = root / "skills" / "open-skill-router" / "references" / "roles"
    for rid in sorted(reg.roles):
        out[refs / f"{rid}.md"] = role_playbook(reg, rid)
        out[root / "skills" / "open-skill-standards" / "references" / f"{rid}.md"] = constitution_fragment(reg, rid)
    out[refs / "README.md"] = roles_index(reg)
    for name, sch in schemas.all_schemas(reg.taxonomy).items():
        out[root / "spec" / "schemas" / f"{name}.schema.json"] = json.dumps(sch, indent=2) + "\n"
    out[root / "dist" / "graph.json"] = json.dumps(index.graph_json(reg), indent=1, ensure_ascii=False) + "\n"
    out[root / "dist" / "graph.mmd"] = index.graph_mermaid(reg)
    return out


def write_all(reg, root: Path) -> list[Path]:
    written = []
    for path, text in outputs(reg, root).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists() or path.read_text() != text:
            path.write_text(text)
            written.append(path)
    db = Path(root) / "dist" / "index.db"
    db.unlink(missing_ok=True)
    index.build_index(reg, path=str(db)).close()
    return written


def stale(reg, root: Path) -> list[Path]:
    return [p for p, text in outputs(reg, root).items() if not p.exists() or p.read_text() != text]
